# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'naturpoint' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for naturpoint


  target 'naturpointTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'naturpoint-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for naturpoint-tvOS

  target 'naturpoint-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
